FROM mate_dev_base

LABEL org.opencontainers.image.title="MATE development environment" \
      org.opencontainers.image.description="Thin non-root user layer for MATE development" \
      org.opencontainers.image.source="https://github.com/MooreThreads/mate"

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

ARG USERNAME=devuser
ARG USER_UID=1000
ARG USER_GID=1000

USER root

COPY --chmod=0755 docker/create-dev-user.sh /usr/local/sbin/mate-create-dev-user

RUN /usr/local/sbin/mate-create-dev-user \
        "${USERNAME}" "${USER_UID}" "${USER_GID}"

ENV HOME=/home/${USERNAME} \
    VIRTUAL_ENV=/home/${USERNAME}/.venv \
    NPM_CONFIG_PREFIX=/home/${USERNAME}/.local \
    PATH=/home/${USERNAME}/.venv/bin:/home/${USERNAME}/.local/bin:${PATH}

USER ${USERNAME}
WORKDIR /workspace/mate
CMD ["sleep", "infinity"]
